#pragma once

#ifndef CONFIG_H
#define CONFIG_H

#define BLUETOOTH_LOGGING_ENABLED 0
#define BLUETOOTH_TUNING_ENABLED 0

#define BRAKING_ENABLED 1
#define GAPS_ENABLED 1
#define USE_I2C_ADAPTER 1
#define USE_ANALOG_READINGS 0

#define ADAPTER_ADDRESS 0x20
#define SERIAL_BAUD_RATE 115200

#define TURN_SPEED_REDUCTION_ENABLED 1

#endif